import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LiffProvider } from "@/components/custom/provider/LiffProvider";
import { Toaster } from "@/components/ui/sonner";
import AppBar from "@/components/custom/app-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LIFF App for App Router",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LiffProvider liffId={process.env.NEXT_PUBLIC_LIFF_ID || ""}>
          <AppBar />

          {children}

          <Toaster />
        </LiffProvider>
      </body>
    </html>
  );
}
